### ISSUE TITLE
Condor job environment variables

### ISSUE THREAD

**Issue by schuhschuh** [openmole/gridscale#6]
Could the [getenv](http://research.cs.wisc.edu/htcondor/manual/v7.6/condor_submit.html#man-condor-submit-getenv) command be of any use ? It would automatically add all my local environment variables to the ClassAd (whatever that is…). At least an option in the CondorEnvironment to enable this flag would be useful. Also nice would of course be to actually be able to pass environment variables similar to the requirements specification to the submit script generated by GridScale.

See also [this article](http://research.cs.wisc.edu/htcondor/manual/v7.6/2_5Submitting_Job.html#SECTION00355000000000000000).

**Comment by jopasserat** [comment]
OK sorry for the delay I followed a wrong track yesterday.

This problem is actually perfectly independent from GridScale. GridScale will always force the loading of the .bashrc file because it needs it to perform the **job submission**. We assume that the user will have an bash environment from where he can submit jobs and this might imply defining a custom `PATH`. 

However, this is not true anymore at the OpenMOLE level. OpenMOLE's mechanisms take the lead once the job has been successfully submitted and there the choice was made not to force the environment or to preserve the system's default behaviour.

Problem is OpenMOLE is thought to submit jobs no matter of their underlying execution environment. A job running on the grid could not rely on local environment variables for instance. 

The SystemExecTask enables you to specify some environment variable for the task but the ScalaTask does not at the moment.

**Comment by schuhschuh** [comment]
So I take it that you reject adding an "environment" list or "getenv" option to the CondorEnvironment?

If environment variables could be set as part of a any task, this wouldn't be needed at the more global environment level. On the other hand, if you could pass it to the CondorEnvironment, none of the specific OpenMOLE Task implementations would explicitly need to support it. I could just use different environment instances if necessary.

> Problem is OpenMOLE is thought to submit jobs no matter of their underlying execution environment. A job running on the grid could not rely on local environment variables for instance.

I still have to configure this environment and tell OpenMOLE about my particular setup.

> This problem is actually perfectly independent from GridScale.

Depends on your point of view.

IMHO, given that GridScale/OpenMOLE have a concept of abstracted "environment" on which specific execution jobs of tasks are being executed, I should be able to specify everything necessary about the installation and configuration of this environment as part of a specific instance of such environment. This should in particular also include environment variables (**as the name already implies**).

**Comment by jopasserat** [comment]
fixed in e1da29f5827c4847bbe0b6f95d5ffba13a11504b #soonerorlater
